window.SM_SEED={
sm_products:[
['طبق الدونات','Donut disc',420,'parts','حبة','piece'],['السست مقاس 18 الكبير','Large springs size 18',9,'parts','حبة','piece','trampoline'],['السست مقاس 13','Springs size 13',7,'parts','حبة','piece','trampoline'],['ونش التسلق','Climbing winch',12000,'games','قطعة','piece'],['جدار التسلق','Climbing wall',7000,'games','قطعة','piece','climb'],['الكور','Play balls',0.04,'parts','حبة','ball'],['مكعب إسفنج أصفر 17 × 17 سم','Yellow foam cube 17 × 17 cm',2.5,'safety','حبة','piece','foam'],['مكعب إسفنج وردي 17 × 17 سم','Pink foam cube 17 × 17 cm',5,'safety','حبة','piece'],['مكعب إسفنج سماوي 17 × 17 سم','Blue foam cube 17 × 17 cm',3.5,'safety','حبة','piece'],['سياكل المسارات','Track bicycles',450,'games','سيكل','bicycle'],['محطة البنزين','Play petrol station',800,'games','قطعة','piece'],['الصرافة','Play ATM',800,'games','قطعة','piece'],['لوحة إشارة المرور','Traffic light sign',1200,'games','قطعة','piece'],['شجرة العسل','Honey tree',15000,'games','قطعة','piece'],['الديسرينة','Diserina',12000,'games','قطعة','piece'],['الشبك الأبيض والأسود','White and black safety net',50,'safety','متر','metre'],['قطعة التسلق','Climbing hold',18,'parts','حبة','piece'],['جدار التسلق الصغير','Small climbing wall',3000,'games','قطعة','piece','climb'],['عمود الفوم','Foam column',50,'safety','حبة','piece'],['قماش الترامبولين','Trampoline fabric',350,'parts','متر','metre','trampoline'],['رمال البورسلان 25 كجم','Porcelain sand 25 kg',150,'parts','كيس','bag'],['زحليقة مضيئة 3 فتحات بطول 3 أمتار','Illuminated triple slide 3 metres',6000,'games','قطعة','piece','slide'],['زحليقة 3 فتحات بطول 5 أمتار','Triple slide 5 metres',9500,'games','قطعة','piece','slide'],['كوع الزحليقة الدائرية','Circular slide elbow',950,'parts','كوع','elbow'],['اللعبة الهوائية','Inflatable play structure',19000,'games','قطعة','piece','inflatable'],['حبة الملاكمة 33 سم × ارتفاع 1.20 متر','Punching obstacle 33 cm × 1.20 m',320,'games','حبة','piece'],['باب متحرك','Moving gate',600,'parts','قطعة','piece'],['سلم ارتفاع 60 سم × عرض 90 سم','Steps 60 cm high × 90 cm wide',850,'parts','قطعة','piece'],['أرضيات حماية سماكة 2 سم','Protective flooring 2 cm thick',55,'safety','متر','metre'],['حاجز الرمل 1.10 م × 2.44 م × 20 سم','Sand barrier 1.10 m × 2.44 m × 20 cm',1400,'safety','حبة','piece'],['مدخل الرمل 90 × 90 × ارتفاع 20 سم','Sand entrance 90 × 90 × 20 cm',850,'parts','قطعة','piece'],['قطعة تلفريك كاملة مع الواير والماكينة','Complete zipline with cable and machine',3500,'games','قطعة','piece','zipline'],['أحزمة التسلق','Climbing harnesses',450,'safety','حزام','harness'],['رمال طبية معالجة 50 كجم','Treated medical sand 50 kg',400,'parts','كيس','bag']
].map((r,i)=>({id:`00000000-0000-4000-8000-${String(i+1).padStart(12,'0')}`,name_ar:r[0],name_en:r[1],price:r[2],category:r[3],unit_ar:r[4],unit_en:r[5],image:r[6]?`assets/product-${r[6]}.png`:'',description_ar:'',description_en:'',aliases:'',featured:!!r[6],published:true})),
sm_centers:[['الرياض','Riyadh',['مركز سي سو للترفيه','يلو زون للترفيه','ملاهي المرح','هابي للترفيه','ماما جيجي','أفاتار – فرع الثمامة','أفاتار – فرع الندى','أفاتار – طريق خريص','المرح السريع','كوكب الألعاب','مدينة القفز','صُنّاع البسمة للترفيه','مودي لاند','هابي للترفيه – طريق جراب','هابي للترفيه – طريق الحاير']],['الباحة','Al Baha',['Go Kidi – فرع الباحة','عالم الترامبولين']],['أبها','Abha',['صُنّاع البسمة للترفيه']],['المدينة المنورة','Madinah',['الطفل الطائر','مدينة البوليفارد','صُنّاع البسمة للترفيه']],['جدة','Jeddah',['قفزة مرح','مدرسة رواء العالمية']],['مكة المكرمة','Makkah',['مربع بسيط']],['حائل','Hail',['يلو للترفيه']],['حفر الباطن','Hafar Al Batin',['لعبة وطفل']],['الخبر','Khobar',['النجمة الصغيرة']],['الدوادمي','Dawadmi',['طفل وفرح']],['جازان','Jazan',['سمايل تاون – جازان']],['أبو عريش','Abu Arish',['سمايل تاون – أبو عريش']],['العارضة','Al Aridhah',['سمايل تاون – العارضة']],['محايل عسير','Muhayil Asir',['واحة المرح']],['خميس مشيط','Khamis Mushait',['هيا طفلي','مركز هوبا']],['المنسك','Al Mansak',['Go Kidi – فرع المنسك']]].flatMap(([city_ar,city_en,names])=>names.map(name_ar=>({name_ar,name_en:name_ar,city_ar,city_en,image:'',published:true}))).map((r,i)=>({...r,id:`10000000-0000-4000-8000-${String(i+1).padStart(12,'0')}`})),
sm_pages:[
{id:'20000000-0000-4000-8000-000000000001',slug:'hero',title_ar:'كل ما يحتاجه مشروعك الترفيهي',title_en:'Everything your play project needs',body_ar:'ألعاب حركية، تجهيزات وقطع غيار في مكان واحد.',body_en:'Play equipment, installations and spare parts in one place.',image:'assets/hero.png',published:true},
{id:'20000000-0000-4000-8000-000000000002',slug:'about',title_ar:'من نحن',title_en:'About us',body_ar:'نحن مصنع متخصص في تصميم وتجهيز الألعاب الحركية للأطفال. نخدم رواد الأعمال والمدارس والحضانات والمراكز التجارية ومراكز الترفيه في مختلف مناطق المملكة. نبدأ بدراسة الموقع وتصميم ثلاثي الأبعاد ثم التصنيع والتركيب والتسليم والمتابعة.',body_en:'We design and manufacture active play equipment for children, serving entrepreneurs, schools, nurseries, malls and entertainment centres across Saudi Arabia. Our process covers site planning, 3D design, manufacturing, installation and after-sales support.',image:'',published:true},
{id:'20000000-0000-4000-8000-000000000003',slug:'services',title_ar:'ماذا نقدم؟',title_en:'Our services',body_ar:'تصميم الصالات الداخلية • سوفت بلاي • تسلق وقفز وزحاليق • ترامبولين • ملاعب كرة قدم للأطفال • ألعاب تعليمية وذكاء • تصميم حسب المساحة والميزانية.',body_en:'Indoor play areas • Soft play • Climbing, jumping and slides • Trampolines • Children’s football areas • Educational activities • Layouts tailored to your space and budget.',image:'',published:true},
{id:'20000000-0000-4000-8000-000000000004',slug:'terms',title_ar:'شروط الطلب',title_en:'Order terms',body_ar:'الطلب المرسل هو طلب عرض سعر للمراجعة. يتم تأكيد التوفر والشحن والمعالجة الضريبية والإجمالي النهائي قبل الدفع. لا يُطلب تحويل مالي قبل استلام عرض السعر المعتمد.',body_en:'Your submission is a quotation request. Availability, shipping, tax treatment and the final total are confirmed before payment. Do not transfer funds before receiving an approved quotation.',image:'',published:true}
],
sm_settings:[{id:'global',brand_ar:'صُنّاع البسمة للترفيه',brand_en:'Smile Makers',whatsapp:'',instagram:'https://www.instagram.com/fun_maker2010',payment_ar:'نرسل بيانات التحويل وعرض السعر بعد مراجعة الطلب.',payment_en:'Bank details and a quotation are provided after reviewing your request.',shipping_ar:'تُحدد تكلفة الشحن ومدة التوصيل بعد مراجعة موقع المشروع والمنتجات.',shipping_en:'Shipping cost and delivery time are confirmed after reviewing your location and items.'}]
};
